[package]
name = "cargo-semantic-release"
version = "0.1.0"
description = "Plugin for Cargo to create semantic release"
edition = "2021"
authors = ["Kristof Kovacs <kristof.kovacs1996@gmail.com>"]
license-file = "LICENSE"

[dependencies]
git2 = "0.20.0"

[dev-dependencies]
tempfile = "3.16.0"

[workspace.metadata.spellcheck]
config = "spellcheck.toml"
