[package]
name = "cargo-semantic-release"
description = "Plugin for Cargo to create semantic release"
license = "MIT"
license-file = "LICENSE"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.20.0"
